site_name: ProjectKaren.Ai Docs
site_url: https://projectkaren.ai/
repo_url: https://github.com/lnxusr1/karen-ai/

theme: 
    name: readthedocs
    highlightjs: true

nav:
    - Introduction: 'index.md'
    - Installation:
      - Basic Install: 'installation.basic.md'
      - Audio/Video Extras: 'installation.audio.md'
      - Raspberry Pi Notes: 'installation.raspberrypi.md'
    - Starting Up: 'karen.md'
    - Training your Watcher: 'karen.watcher.train.md'
    - Configuration Files:
      - Overview: 'config.overview.md'
      - Audio-only Example: 'config.example.md'
      - Audio/Video Example: 'config.example.video.md'
    - Operations:
      - Custom Devices: 'karen.devices.md'
    - Skills:
      - Creating your own Skill: 'karen.skill.md'
    - Links:
      - '@ Code': 'https://projectkaren.ai/code'
      - '@ Community': 'https://projectkaren.ai/discussion'
      - '@ Bugs & Issues': 'https://projectkaren.ai/issues'
      - '@ ProjectKaren.Ai': 'https://projectkaren.ai'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("src")
