site_name: ProjectKaren.Ai Docs
site_url: https://projectkaren.ai/
repo_url: https://github.com/lnxusr1/karen/

theme: 
    name: readthedocs
    highlightjs: true

nav:
    - Introduction: 'index.md'
    - Installation:
      - Basic Install: 'installation.basic.md'
      - Audio/Video Extras: 'installation.audio.md'
      - Raspberry Pi Notes: 'installation.raspberrypi.md'
    - Starting Up: 'karen.md'
    - Training your Watcher: 'karen.watcher.train.md'
    - Configuration Files:
      - Overview: 'config.overview.md'
      - Audio-only Example: 'config.example.md'
      - Audio/Video Example: 'config.example.video.md'
    - Operations:
      - karen.Brain: 'karen.brain.md'
      - karen.DeviceContainer: 'karen.device.md'
    - Devices:
      - karen.listener.Listener: 'karen.listener.md'
      - karen.speaker.Speaker: 'karen.speaker.md'
      - karen.watcher.Watcher: 'karen.watcher.md'
    - Functions:
      - Skill Manager: 'karen.skillmanager.md'
      - Shared Library: 'karen.shared.md'
    - Handlers: 'karen.handlers.md'
    - Skills:
      - Skill Template: 'karen.skill.md'
      - HelloSkill: 'karen.skills.helloskill.md'
      - KnockKnockSkill: 'karen.skills.knockknockskill.md'
      - TellDateTimeSkill: 'karen.skills.telldatetimeskill.md'
    - Links:
      - '@ Code': 'https://projectkaren.ai/code'
      - '@ Community': 'https://projectkaren.ai/discussion'
      - '@ Bugs & Issues': 'https://projectkaren.ai/issues'
      - '@ ProjectKaren.Ai': 'https://projectkaren.ai'

plugins:
- search
- mkdocstrings
